"""Interface da auditoria de outputs financeiros produzidos por IA."""

import pandas as pd
import plotly.express as px
import streamlit as st

from src.ai_audit import (
    auditar_portfolio_por_sharpe,
    auditar_resultado,
)
from src.portfolio import avaliar_portfolio
from ui.charts import configurar_figura


def render_audit(resultados):
    """
    Renderiza a interface de auditoria de outputs externos de IA.

    O QuantGuard calcula benchmarks quantitativos de forma independente
    e compara esses benchmarks com valores fornecidos pelo usuário.
    """

    teste = resultados["teste"]
    var_hist = resultados["var_hist"]
    resultado_max_sharpe = resultados["resultado_max_sharpe"]
    preco_black_scholes = resultados["preco_black_scholes"]
    taxa_livre_risco_teste = resultados["taxa_livre_risco_teste"]

    # ========================================================
    # CABEÇALHO
    # ========================================================

    st.markdown("## AI Financial Audit")

    st.caption(
        "Validate financial estimates generated by external AI models "
        "against independent quantitative benchmarks."
    )

    st.info(
        "QuantGuard does not generate the AI response. "
        "Enter outputs produced by an external AI model below. "
        "Results are recalculated automatically whenever an input changes."
    )

    # ========================================================
    # INPUTS EXTERNOS DA IA
    # ========================================================

    st.markdown("### External AI Outputs")

    col_var, col_option = st.columns(2)

    with col_var:
        valor_ia_var = st.number_input(
            "AI estimate · Historical VaR (R$)",
            min_value=0.0,
            value=None,
            step=100.0,
            placeholder="Enter AI estimate",
            key="ai_var_input",
        )

    with col_option:
        valor_ia_option = st.number_input(
            "AI estimate · European Call Price",
            min_value=0.0,
            value=None,
            step=0.01,
            format="%.4f",
            placeholder="Enter AI estimate",
            key="ai_option_input",
        )

    # ========================================================
    # PORTFÓLIO SUGERIDO PELA IA
    # ========================================================

    st.markdown("### AI Portfolio Allocation")

    st.caption(
        "Enter the portfolio weights suggested by the external AI model. "
        "The allocation must sum to 100%."
    )

    colunas = st.columns(len(teste.columns))

    peso_padrao = 100.0 / len(teste.columns)

    pesos_percentuais = {}

    for coluna, ticker in zip(colunas, teste.columns):
        with coluna:
            pesos_percentuais[ticker] = st.number_input(
                ticker,
                min_value=0.0,
                max_value=100.0,
                value=peso_padrao,
                step=1.0,
                format="%.2f",
                key=f"ai_weight_{ticker}",
            )

    soma_pesos = sum(pesos_percentuais.values())

    st.caption(
        f"Total allocation: {soma_pesos:.2f}%"
    )

    # ========================================================
    # VALIDAÇÃO DOS INPUTS
    # ========================================================

    if abs(soma_pesos - 100.0) > 0.01:
        st.warning(
            f"Portfolio allocation currently sums to "
            f"{soma_pesos:.2f}%. Adjust the weights to 100%."
        )
        return

    if valor_ia_var is None or valor_ia_option is None:
        st.markdown("### Audit Results")

        st.info(
            "Enter the external AI estimates for VaR and option pricing "
            "to start the quantitative audit."
        )
        return

    # ========================================================
    # AVALIAÇÃO OOS DA CARTEIRA DA IA
    # ========================================================

    pesos_ia = pd.Series(
        {
            ticker: peso / 100
            for ticker, peso in pesos_percentuais.items()
        }
    ).reindex(teste.columns)

    resultado_portfolio_ia = avaliar_portfolio(
        pesos=pesos_ia,
        retornos=teste,
        taxa_livre_risco=taxa_livre_risco_teste,
    )

    sharpe_quant = resultado_max_sharpe["sharpe"]
    sharpe_ia = resultado_portfolio_ia["sharpe"]

    # ========================================================
    # AUDITORIAS
    # ========================================================

    auditoria_var = auditar_resultado(
        nome_teste="Historical VaR",
        valor_referencia=var_hist,
        valor_ia=valor_ia_var,
    )

    auditoria_option = auditar_resultado(
        nome_teste="Option Pricing",
        valor_referencia=preco_black_scholes,
        valor_ia=valor_ia_option,
    )

    auditoria_portfolio = auditar_portfolio_por_sharpe(
        sharpe_referencia=sharpe_quant,
        sharpe_ia=sharpe_ia,
    )

    score_var = auditoria_var["score_numerico"]
    score_option = auditoria_option["score_numerico"]
    score_portfolio = auditoria_portfolio["score_numerico"]

    score_geral = (
        score_var
        + score_option
        + score_portfolio
    ) / 3

    # ========================================================
    # RESULTADOS
    # ========================================================

    st.markdown("### Audit Results")

    c1, c2, c3 = st.columns(3)

    with c1:
        st.metric(
            "PORTFOLIO",
            f"{score_portfolio:.1f}/100",
        )

        st.write(
            f"**{auditoria_portfolio['classificacao']}**"
        )

        st.caption(
            f"Quant OOS Sharpe: {sharpe_quant:.3f} | "
            f"AI OOS Sharpe: {sharpe_ia:.3f}"
        )

    with c2:
        st.metric(
            "VALUE AT RISK",
            f"{score_var:.1f}/100",
        )

        st.write(
            f"**{auditoria_var['classificacao']}**"
        )

        st.caption(
            f"Quant benchmark: R$ {var_hist:,.2f} | "
            f"AI estimate: R$ {valor_ia_var:,.2f}"
        )

    with c3:
        st.metric(
            "OPTION PRICING",
            f"{score_option:.1f}/100",
        )

        st.write(
            f"**{auditoria_option['classificacao']}**"
        )

        st.caption(
            f"Black-Scholes: {preco_black_scholes:.4f} | "
            f"AI estimate: {valor_ia_option:.4f}"
        )

    # ========================================================
    # RELIABILITY OVERVIEW
    # ========================================================

    st.markdown("### Reliability Overview")

    score_df = pd.DataFrame(
        {
            "Audit": [
                "Portfolio",
                "VaR",
                "Option Pricing",
            ],
            "Score": [
                score_portfolio,
                score_var,
                score_option,
            ],
        }
    )

    fig_audit = px.bar(
        score_df,
        x="Audit",
        y="Score",
        text_auto=".1f",
        range_y=[0, 100],
    )

    configurar_figura(
        fig_audit,
        x_title=None,
        y_title="Reliability Score",
    )

    st.plotly_chart(
        fig_audit,
        use_container_width=True,
    )

    # ========================================================
    # SCORE GERAL
    # ========================================================

    st.markdown("### Overall Assessment")

    st.metric(
        "AI RELIABILITY SCORE",
        f"{score_geral:.1f}/100",
    )

    if score_geral >= 95:
        st.success(
            "PASS — the evaluated outputs are closely aligned "
            "with the quantitative benchmarks."
        )

    elif score_geral >= 85:
        st.warning(
            "REVIEW — some outputs require additional "
            "human financial review."
        )

    else:
        st.error(
            "FAIL — material deviations from the quantitative "
            "benchmarks were identified."
        )

    st.caption(
        "PASS/REVIEW/FAIL thresholds are project-defined validation "
        "rules and do not represent regulatory or industry standards."
    )